
services:
  db:
    image: postgres:16
    container_name: api_postgres
    restart: always
    shm_size: 128mb

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_pass
      POSTGRES_DB: api_db

    volumes:
      - platform_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  platform_data:
